# These are defaults for truenas-csi.
# For customization, place/override variables in local.yaml

# default fstype for volumes, ext2/3/4, or xfs
fstype: ext4

# images configuration
images:
  driver:
    image: ghcr.io/dravanet/truenas-csi:0.2.3

  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0

  attacher:
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0

  resizer:
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0

  node-driver-registrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0

podAnnotations: {}
