# These are defaults for truenas-csi.
# For customization, place/override variables in local.yaml

# default fstype for volumes, ext2/3/4, or xfs
fstype: ext4

# images/components configuration
images:
  driver:
    image: ghcr.io/dravanet/truenas-csi:0.4.0

  provisioner:
    image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
    workers: 1
    timeout: 1m
    # These provide parameters for controller deployment/pod
    nodeSelector: {}
    tolerations: []

  attacher:
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0

  resizer:
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    workers: 1
    timeout: 1m

  node-driver-registrar:
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
    # These provide parameters for node daemonset/pods
    nodeSelector: {}
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists

podAnnotations: {}
