# These are defaults for truenas-csi.
# For customization, place/override variables in local.yaml

# default fstype for volumes, ext2/3/4, or xfs
fstype: ext4

# images/components configuration
images:
  driver:
    image: ghcr.io/dravanet/truenas-csi:0.5.1

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
    workers: 1
    timeout: 1m
    # These provide parameters for controller deployment/pod
    nodeSelector: {}
    tolerations: []

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.3.0

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
    workers: 1
    timeout: 1m

    resources:
      requests:
        cpu: 10m
        memory: 32Mi

  node-driver-registrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
    # These provide parameters for node daemonset/pods
    nodeSelector: {}
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists

    resources:
      requests:
        cpu: 5m
        memory: 16Mi

podAnnotations: {}
