apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "truenas-csi.fullname" . }}-controller
  labels:
    {{- include "truenas-csi.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
      {{- include "truenas-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configuration-hash: "{{ .Values.controller | toYaml | adler32sum }}"
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        component: controller
        {{- include "truenas-csi.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "truenas-csi.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.driver.image }}
          env:
            - name: "CONTROLLER_CONFIG"
              value: /config/controller.yml
          securityContext:
            runAsNonRoot: true
            runAsUser: 21609
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: controller-config
              mountPath: /config

        - name: csi-provisioner
          image: {{ .Values.images.provisioner.image }}
          args:
            - "--csi-address=/csi/csi.sock"
            - "--default-fstype={{ .Values.fstype }}"
            - "--leader-election"
            - "--http-endpoint=:8080"
            - "--worker-threads={{ .Values.images.provisioner.workers }}"
            - "--timeout={{ .Values.images.provisioner.timeout }}"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - containerPort: 8080
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20

        - name: csi-attacher
          image: {{ .Values.images.attacher.image }}
          args:
            - "-csi-address=/csi/csi.sock"
            - "-leader-election"
            - "-http-endpoint=:8082"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - containerPort: 8082
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20

        - name: csi-resizer
          image: {{ .Values.images.resizer.image }}
          args:
            - "--csi-address=/csi/csi.sock"
            - "--leader-election"
            - "--http-endpoint=:8081"
            - "--workers={{ .Values.images.resizer.workers }}"
            - "--timeout={{ .Values.images.resizer.timeout }}"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - containerPort: 8081
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20

      {{- with index .Values.images "provisioner" }}
      {{- with .tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: controller-config
          secret:
            secretName: {{ include "truenas-csi.fullname" . }}-config
