---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "truenas-csi.fullname" . }}-node
spec:
  selector:
    matchLabels:
      component: node
      {{- include "truenas-csi.selectorLabels" . | nindent 6 }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: node
        {{- include "truenas-csi.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.driver.image }}
          env:
            - name: CSI_NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          {{- include "container.resources" .Values.images.driver }}

          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: volume-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: host-root
              mountPath: /host
              mountPropagation: Bidirectional
            - name: host-dev
              mountPath: /dev

        - name: csi-node-driver-registrar
          image: {{ (index .Values.images "node-driver-registrar").image }}
          args:
            - "-csi-address=/csi/csi.sock"
            - "-kubelet-registration-path=/var/lib/kubelet/plugins/truenas-csi.dravanet.net/csi.sock"
          {{- include "container.resources" (index .Values.images "node-driver-registrar") }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration

      priorityClassName: system-node-critical

      {{- with index .Values.images "node-driver-registrar" }}
      {{- with .tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/truenas-csi.dravanet.net
            type: DirectoryOrCreate
        - name: volume-dir
          hostPath:
            path: /var/lib/kubelet
        - name: host-root
          hostPath:
            path: /
        - name: host-dev
          hostPath:
            path: /dev
