apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "truenas-csi.fullname" . }}-config
stringData:
  controller.yml: |
    {{- .Values.controller | toYaml | nindent 4}}
